//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public class @new 
{
}

/// <remarks/>
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public class tv 
{   
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("channel")]
    public channelType[] channel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("programme")]
    public programmeType[] programme;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-info-url")]
    public string sourceinfourl;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-info-name")]
    public string sourceinfoname;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-data-url")]
    public string sourcedataurl;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("generator-info-name")]
    public string generatorinfoname;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("generator-info-url")]
    public string generatorinfourl;
}

/// <remarks/>
public class channelType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("display-name")]
    public displaynameType[] displayname;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("icon")]
    public iconType[] icon;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("url")]
    public string[] url;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="display-nameType")]
public class displaynameType 
{
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
public class iconType 
{   
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height;
}

/// <remarks/>
public class programmeType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("title")]
    public titleType[] title;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub-title")]
    public subtitleType[] subtitle;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("desc")]
    public descType[] desc;
    
    /// <remarks/>
    public creditsType credits;
    
    /// <remarks/>
    public string date;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category")]
    public categoryType[] category;
    
    /// <remarks/>
    public languageType language;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("orig-language")]
    public origlanguageType origlanguage;
    
    /// <remarks/>
    public lengthType length;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("icon")]
    public iconType[] icon;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("url")]
    public string[] url;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("country")]
    public countryType[] country;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("episode-num")]
    public episodenumType episodenum;
    
    /// <remarks/>
    public videoType video;
    
    /// <remarks/>
    public audioType audio;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("previously-shown")]
    public previouslyshownType previouslyshown;
    
    /// <remarks/>
    public premiereType premiere;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-chance")]
    public lastchanceType lastchance;
    
    /// <remarks/>
    public @new @new;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("subtitles")]
    public subtitlesType[] subtitles;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rating")]
    public ratingType[] rating;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("star-rating")]
    public starratingType starrating;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("start")]
    public string start;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("stop")]	
    public string stop;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("pdc-start")]
    public string pdcstart;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("vps-start")]
    public string vpsstart;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string showview;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string videoplus;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string channel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0/1")]
    public string clumpidx = "0/1";
}

/// <remarks/>
public class titleType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="sub-titleType")]
public class subtitleType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
public class descType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
public class creditsType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("director")]
    public string[] director;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("actor")]
    public string[] actor;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("writer")]
    public string[] writer;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adapter")]
    public string[] adapter;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("producer")]
    public string[] producer;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("presenter")]
    public string[] presenter;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("commentator")]
    public string[] commentator;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("guest")]
    public string[] guest;
}

/// <remarks/>
public class categoryType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
public class languageType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="orig-languageType")]
public class origlanguageType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
public class lengthType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public lengthTypeUnits units;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
public enum lengthTypeUnits 
{ 
    /// <remarks/>
    seconds,
    
    /// <remarks/>
    minutes,
    
    /// <remarks/>
    hours,
}

/// <remarks/>
public class countryType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="episode-numType")]
public class episodenumType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("onscreen")]
    public string system = "onscreen";
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
public class videoType 
{    
    /// <remarks/>
    public string present;
    
    /// <remarks/>
    public string colour;
    
    /// <remarks/>
    public string aspect;
}

/// <remarks/>
public class audioType 
{    
    /// <remarks/>
    public string present;
    
    /// <remarks/>
    public string stereo;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="previously-shownType")]
public class previouslyshownType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string start;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string channel;
}

/// <remarks/>
public class premiereType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="last-chanceType")]
public class lastchanceType 
{    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
public class subtitlesType 
{    
    /// <remarks/>
    public languageType language;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public subtitlesTypeType type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified;
}

/// <remarks/>
public enum subtitlesTypeType 
{    
    /// <remarks/>
    teletext,
    
    /// <remarks/>
    onscreen,
}

/// <remarks/>
public class ratingType 
{    
    /// <remarks/>
    public string value;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("icon")]
    public iconType[] icon;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string system;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="star-ratingType")]
public class starratingType 
{    
    /// <remarks/>
    public string value;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("icon")]
    public iconType[] icon;
}
